# Requires sudo for CUDA install
dist: trusty
sudo: required

# CPP language
language: cpp

# Compiler matrix for recent GCC versions
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: GCC_VERSION =g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: GCC_VERSION=g++-5

# Install CUDA
install: 
 - chmod +x ./scripts/travis_install.sh
 - sudo -E ./scripts/travis_install.sh

# Build steps
script: "make BOOST_TEST HOST_COMPILER=$GCC_VERSION"
