# Specify version format
version: "0.1.{build}"

# Operating system (build VM template)
os: Visual Studio 2013

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  # - Win32 Diable Win32
  - x64

# specify custom environment variables
environment:
  BOOST_DIR: C:\Libraries\boost_1_59_0
  CUDA_REPO_PKG_REMOTE: https://developer.nvidia.com/compute/cuda/8.0/prod/network_installers/cuda_8.0.44_windows_network-exe
  CUDA_REPO_PKG_LOCAL: cuda_8.0.44_win10_network.exe

# build configuration, i.e. Debug, Release, etc.
configuration:
  - BoostTest

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\FLAMEGPU2_dev

# scripts that run after cloning repository
install:
  - ps: Write-Host 'Downloading CUDA Network Installer'
  - ps: Invoke-WebRequest $env:CUDA_REPO_PKG_NETWORK -OutFile $env:CUDA_REPO_PKG_LOCAL | Out-Null
  - ps: Write-Host 'Downloading Complete'
  - ps: Write-Host 'Installing CUDA Compiler and Runtime'
  - ps: .\$env:CUDA_REPO_PKG_LOCAL -s compiler_8.0 visual_studio_integration_8.0 command_line_tools_8.0 cudart_8.0 | Out-Null
  - ps: Write-Host 'Installation Complete.'

# The build
build:
  project: C:\projects\FLAMEGPU2_dev\FLAMEGPU2.sln # path to Visual Studio solution or project

#debugging
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
